project:
  type: website

blog:
  title: "Blog"
  file: blog.qmd
  listing:
    contents: posts
    sort: "date desc"
    type: default
    categories: true
    feed: true

website:
  search: false
  navbar:
    background: light
    title: "<span class='site-title'>Ezra Tandela 陈主荣</span>"
    right:
      - href: index.qmd
        text: About
      - href: work.qmd
        text: Work
      - href: blog.qmd
        text: Blog
  page-footer: 
    center: "
      <div style='text-align: center;'>
        &copy; 2025 Ezra Tandela<br>
        Contact: <a href='mailto:ezratandela@g.harvard.edu'>ezratandela@g.harvard.edu</a>
      </div>"


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
