---
title: "Work"
css: work-custom.css

---

## Education
__Harvard University__ 
Ph.D. Comparative Literature 

__University of California Los Angeles__ 
M.A. East Asian Studies
 
## Presentations

“Dangers of Metropolitan Aspirations in Colonial Taiwan and Korea: Kim Saryang’s ‘Pegasus’
and Long Yingzong’s ‘Evening Moon’.
” Conference paper, Arizona State University East Asian
Studies Graduate Student Conference, January 13-14, 2023.

## Translations

“Theorizing Asiatic Contradiction, UX of Contemporary Korean Literature” by Hoduk Hwang.
Translated by Ezra Tandela. In Symplokē 30 No. 1-2.

“A Koreanizing World? 82nyŏnsaeng Kim Chiyŏng (Kim Ji-young, Born 1982) and Asian Values” by Hoduk Hwang. Translated by Ezra Tandela. In Critical Asia Archives: Events and Theories June 2021 (https://caarchives.org/a-koreanizing-world-ux-of-contemporary-korean-literature-and-asias-calling/)

## Ongoing Projects

Transnational History of Decolonial in Asia from 1950-1975

## Languages

Korean: Native-level fluency    
English: Native-level fluency   
Chinese: Native-level fluency  
Japanese: Fluent  
Indonesian: Fluent  
Classical Chinese: Advanced reading proficiency    
Classical Japanese: Intermediate reading proficiency