---
title: "Book Reviews of David Wang's <em>Fin-De-Sìecle Splendor: Repressed Modernities of Late Qing Fiction</em> (1997) and <em>The Transformation of the Narrative Pattern of Chinese Novels (Zhongguo xiaoshuo xushu moshi de zhuanbian)</em> (1988)"
css: styles.css
author: "Ezra Tandela"
date: "2024-03-25"
categories: [book review]
---

In this essay, I will be reviewing two highly influential monographs in the study of Chinese literary modernity: Chen Pingyuan’s The Transformation of the Narrative Pattern of Chinese Novels <em>Zhongguo xiaoshuo xushu moshi de zhuanbian</em> (1988) and David Wang’s <em>Fin-De-Sìecle Splendor: Repressed Modernities of Late Qing Fiction</em> (1997). Chen’s book studies the adoption of Western narrative techniques in late Qing new fiction and May Fourth fiction. Wang’s monograph presents the alternative trajectories of modernity that have been repressed in the standard literary historiography of modern Chinese fiction by studying neglected genres of late Qing fiction. The two writers emphasize two completely different aspects of Chinese literary modernity. Chen is primarily concerned with the transition between late Qing new fiction, which are often considered the earliest experiments with Western narrative modes, and the succeeding period of May Fourth fiction, which is the beginning of modern Chinese literature in standard literary histories. Whereas Chen focuses on indigenous transformations involved in the modernization of Chinese fiction culminating in May Fourth fiction, Wang argues against the prevailing May Fourth paradigm that suggests a singular path of literary modernization, and instead proposes to uncover “repressed modernities” in late Qing fiction, so as to open up the horizon of what it means for Chinese literature to be “modern.”(Wang 342)  By drawing attention to the literary innovations of late Qing fiction, both writers expand the genealogy of Chinese literary modernity.

In Transformations, Chen studies the development of modern Chinese fiction along three narratological axes: time, perspective, and structure (Chen 4, 26). In chapter two, Chen studies how the translation and adaptation of Western political, mystery, and romance novels in late Qing new fiction introduced new narrative temporalities like inverted and discontinuous storytelling (50). Chen argues that these new narrative sequences started to move away from the linear natural time-order that characterized traditional Chinese fiction (Chen 52-3). By the May Fourth period, writers like Lu Xun and Chen Xianghe went even further from the traditional narrative sequence by experimenting with fragmented narrative sequences that defy linear causal order (Chen 62-3). Chapter three analyzes how the adoption of Western narrative perspectives like limited first-person and third-person narration gradually displaced the omniscient narration of traditional Chinese fiction. Chen shows how late Qing translations of Western mystery and adventure novels modified the originals’ first-person narration into the third person in order to aid the comprehension of readers (Chen 76). Although many new fiction writers adopted limited first-person narration in their travelogue fiction, the narrator merely served as a bystander that would retell past adventures or another character’s story (Chen 78, 80). Unlike new fiction writers, Chen argues that the use of first-person narration in May Fourth fiction foregrounded the interior subjectivity of the narrator (Chen 92). Chen emphasizes that May Fourth writers were more self-conscious in their adoption of limited first-person narration, thereby overcoming the inconsistences present in the new fiction writers’ earlier adaptations of first-person narration (Chen 95, 103). He briefly mentions the influence of the Japanese I-novel on Chinese writers, but, surprisingly, he does not further explore the Japanese connection in this or other sections of his book (Chen 98). In chapter four, Chen describes how modern Chinese fiction slowly moved away from the plot-centered structure of traditional Chinese fiction. He carefully studies new fiction writers’ literary innovations with regards to psychological interiority and landscape but concludes that the dominance of plot inherited from traditional fiction remains largely unchallenged until the May Fourth writers (Chen 121, 123). Citing writers like Lu Xun and Yu Dafu, Chen proposes that May Fourth fiction’s preoccupation with introspective feeling, monologues, and subconscious states evinces a common concern for individual expression, which displaces the centrality of plot in traditional Chinese fiction (Chen 126-8, 134-6). 

Throughout his book, Chen studies the indigenous transformation of traditional Chinese fiction in the wider literary modernization context of emulating Western narrative techniques. On the one hand, Chen’s monograph contains meticulous studies of literary innovations in late Qing new fiction that begin to transform the narrative conventions of traditional Chinese fiction. On the other hand, Chen will usually end his discussion of new fiction by implying the limitations of these literary innovations in comparison to later May Fourth deployments of Western narrative technique. In other words, a linear scheme of literary modernization recurringly appears as a motif in Chen’s description of the transition between late Qing new fiction and May Fourth fiction. However, the richness of the literary innovations in new fiction that Chen himself describes appears to resist this type of schematization. After all, why should these innovations not be considered on their own merit, as opposed to being staged as lesser predecessors of later May Fourth developments? To be sure, Chen himself is quite aware of the difficulty of squaring the many diverse indigenous literary innovations and the genealogy of literary modernization. In chapters five, six, and seven, Chen shifts the focus to the internal transformations of the Chinese literary field (Chen 167). He analyzes how fiction moved from the margins to the center of the literary field, and, in the process, absorbed literary techniques from other classical genres such as anecdotes, comedies, travelogues, and diaries (Chen 203, 217).  

In Fin-De-Siècle, Wang precisely argues against the linear teleological view of literary modernity that is adopted as a main hermeneutic framework by critics like Chen. Against the prevailing paradigm that crowns May Fourth fiction as the origin of modern Chinese novel, Wang analyzes late Qing fiction, not as a “prelude” to modern Chinese literature, but rather as a valuable repository of many possible literary modernities that were subsequently repressed in the polemics of the May Fourth movement (Wang 16). He explores these repressed aspects of Chinese literary modernity by studying the hitherto neglected genres of late Qing fiction: courtesan novel, grotesque exposé, chivalric and court-case tales, and science fantasy (Wang 50). In chapter two, Wang studies the edification of desire in late Qing courtesan novels, particularly how the representation of desire vacillates between excessive eroticization and moral containment of desire (Wang 59, 72). Chapter three argues that the late Qing chivalric and court-case tales explore the contingency and uncertainty of justice in a time of great social change (Wang 121). Wang analyzes how stories like The Travels of Lao Can and Living Hell subvert the conventions of the chivalric and court-case genre by meditating on the equivocity between justice and evil, as well as between law and violence (Wang 150, 180). Interestingly, in stark contrast to Chen’s high appraisal of May Fourth aesthetics, Wang suggests that the May Fourth writers’ harsh criticism of the allegedly conservative orientation of court-case and chivalric tales, and their inability to see the formal innovations in these works, reflect the intellectual poverty of May Fourth ideological polemics (Wang 121). Chapter four studies how the late Qing grotesque exposés reflect the crises in contemporary society in highly stylized manner, through “exaggeration, disfiguration, and metamorphosis.” (Wang 185) Wang argues that the carnivalesque world of these exposés display a playful engagement with the real that stands in stark contrast with the sober revolutionary realism of May Fourth writers (Wang 251). In chapter five, Wang proposes that late Qing science fantasy imagines “new ways of narrating the nation” by adopting new topoi from Western science fiction as well as transforming conventions from traditional Chinese writings on the fantastic (Wang 257-8). In his concluding chapter on reinterpreting contemporary Chinese fiction in light of these late Qing repressed modernities, Wang reminds the reader that he is not seeking to write a new literary history of the modern Chinese novel, but merely arguing for diversifying the interpretive horizon of modern Chinese literature to include more heterogeneous voices (Wang 341-2). 

Even though Wang insists he is not offering a new origin or genealogy of modern Chinese literature, he ultimately expands the purview of the genealogy of modern Chinese fiction. In fact, Wang’s project can be understood as a continuation of the last three chapters of Chen’s monograph, namely the study of indigenous transformations of traditional Chinese fiction. Chen investigates the “silent revolution” taking place among late Qing writers at the turn of the 19th century to show that May Fourth literary innovations have their roots in earlier narrative experiments (Chen 32-3). Wang instead shifts the focus to late Qing texts throughout the second half of the 19th century beyond the canonical new fiction writers; in so doing, he questions the standard literary historiography of modern Chinese fiction and suggests a much more cacophonous picture of Chinese literary modernity. Written in the 1980s against the backdrop of Marxist literary historiography and European formalist narratologies, Chen’s innovative edge lies in his insistence on studying the narratological innovations of Chinese fiction without reducing these developments into social scientific models of cultural modernization or assuming one-to-one emulation of European narrative modes. Wang takes further the question of what makes the literary modernity of modern Chinese literature Chinese by speculating on the alternative paths of Chinese literary modernity. Ultimately, both monographs complicate and enrich our historical understanding of modern Chinese fiction by adopting more expansive views of Chinese literary modernity. 




















